

[env:esp32_microros2]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Compila apenas o publisher.cpp dentro de src/
build_src_filter = -<*> +<main.cpp>

; Configurações do micro-ROS
board_microros_distro = jazzy
; board_microros_transport = serial

board_microros_transport = wifi 
; Para o plugin do micro-ROS saber que é Wi-Fi

; build_flags =
;     -DMICRO_ROS_TRANSPORT_WIFI
;     -I .pio/libdeps/esp32_microros2/micro_ros_platformio/metas

; Chave corrigida para lib_deps
lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio.git


; [env:esp32controller]
; platform = espressif32
; board = esp32dev
; framework = arduino
; monitor_speed = 115200

; build_src_filter = -<*> +<ps4.cpp>
; ; build_src_filter = -<*> +<scanner.cpp>
; lib_deps =
;     https://github.com/pablomarquez76/PS4_Controller_Host


; [env:esp32test]
; platform = espressif32
; board = esp32dev
; framework = arduino

; ; Velocidade do Monitor Serial
; monitor_speed = 115200
; build_src_filter = -<*> +<temperature.cpp>
; lib_deps = 
;     adafruit/DHT sensor library @ ^1.4.6
;     adafruit/Adafruit Unified Sensor @ ^1.1.14